### ISSUE TITLE
Newlines cause `AttributeError: 'BlockParser' object has no attribute 'status'`

### ISSUE THREAD

**Issue by connerxyz** [Python-Markdown/markdown#1091]
Newlines in input throws exception.

```
>>> markdown.markdown("# Fine")
'<h1>Fine</h1>'
>>> markdown.markdown("# Not fine\n\nThis throws exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/U6020643/git/helix/c3-helix_inclusion-protocol/.venv/lib/python3.9/site-packages/markdown/core.py", line 387, in markdown
    return md.convert(text)
  File "/Users/U6020643/git/helix/c3-helix_inclusion-protocol/.venv/lib/python3.9/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/Users/U6020643/git/helix/c3-helix_inclusion-protocol/.venv/lib/python3.9/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/Users/U6020643/git/helix/c3-helix_inclusion-protocol/.venv/lib/python3.9/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/Users/U6020643/git/helix/c3-helix_inclusion-protocol/.venv/lib/python3.9/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/Users/U6020643/git/helix/c3-helix_inclusion-protocol/.venv/lib/python3.9/site-packages/markdown/blockprocessors.py", line 596, in run
    if self.parser.status.isstate('list'):
AttributeError: 'BlockParser' object has no attribute 'status'
```

Seems pretty basic. What am I missing?

**Comment by waylan** [comment]
I'm not seeing that behavior.

```python
>>> markdown.__version__
'3.3.3'
>>> markdown.markdown('# Fine\n\nThis throws exception.')
'<h1>Fine</h1>\n<p>This throws exception.</p>'
```

Although I see you are using Python 3.9, which I don't have readily available. However, all our tests pass on Python 3.9, so I doubt that's it, unless you are using an older version of Python-Markdown which was never tested against Python 3.9.

**Comment by waylan** [comment]
More curious, your traceback suggests that line 596 of `markdown/blockprocessors.py` is `if self.parser.status.isstate('list'):` when in fact it is:

https://github.com/Python-Markdown/markdown/blob/4b836201f0dbf1ce763dae3688dee38f1a39a558/markdown/blockprocessors.py#L596

Notice `state` rather that `status`. I'm not sure where `status` comes from. It has certainly never been present in our commit history. In fact, that block of code hasn't changed since 2008 in 159a274a9. You then need to go back a few more commits to when it was first introduced in ba147ca9b earlier that same year. It has always been `state`, never `status`.

I'm curious if you installed the lib from some other source than [Markdown][1] on PyPI. If so, you will need to report the issue to the maintainer of that source, as they clearly modified the package in some way.

[1]: https://pypi.org/project/Markdown/

**Comment by connerxyz** [comment]
Looks like I corrupted the package somehow. I blew away my virtual environment and recreated the whole thing and it's now working fine. Thanks.
